### ISSUE TITLE
Odd label

### ISSUE THREAD

**Issue by timothyk0908** [popcorn4dinner/php-collections#1]
php-collections/src/AbstractCollection.php:145
`throw new \InvalidArgumentException("Invalid Item: ". __CLASS__ ." cannot collect items that like ". get_class($item));
`

` "that like" should just be "like"
`

**Comment by popcorn4dinner** [comment]
true :-D collections should't worry about which items like which other items.
Feel free to create a PR for this.

**Comment by popcorn4dinner** [comment]
closed with PR #2
